### ISSUE TITLE
Collaborate with vfile?

### ISSUE THREAD

**Issue by ChristianMurphy** [LRNWebComponents/json-outline-schema#2]
The leaf nodes bear a striking resemblance to vfile https://github.com/vfile/vfile
And the overall structure to https://github.com/vfile/vfile-reporter-folder-json

It also looks like json outline schema is being used to represent the file system of a site. (https://www.youtube.com/watch?v=ktlODSnGAOw)
Which is the same reason https://github.com/vfile/vfile-reporter-folder-json was created.

Maybe there is an opportunity to collaborate?

/cc @wooorm

**Comment by btopro** [comment]
hmm... looked through; seems very similar at parts in the reporter-folder-json stuff but ultimately I'm not sure. Our schema isn't really for relationships between file system things (even tho it does have a location attribute). It's more the relationships of things. HAXCMS is already leveraging this within a site (to imply what content to load and visualize as a structure), and then as a site listing (flat list of names, doesn't load content just enough data to stitch together a visual). We're also talking about using it for visualizing mapping information between areas, discussions / comment threading, etc. So it's not exclusively file system.

Thanks for the ping though, nice to see others needing something similar
